export const LOGIN_REQUEST='APP/LOGIN_REQUEST';
export const LOGIN_FAIL='APP/LOGIN_FAIL';
export const LOGIN_SUCCESS='APP/LOGIN_SUCCESS';
export const SIGNUP_REQUEST='APP/SIGNUP_REQUEST';
export const SIGNUP_FAIL='APP/SIGNUP_FAIL';
export const SIGNUP_SUCCESS='APP/SIGNUP_SUCCESS';
